# Generated by Django 2.0.13 on 2019-04-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='japan'),
            preserve_default=False,
        ),
    ]
