# Generated by Django 2.2.1 on 2019-05-26 08:32

import book_summary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bigcategory',
            field=models.ForeignKey(blank=True, default=book_summary.models.set_default_bigcategory, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_summary.BigCategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, default=book_summary.models.set_default_author, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_summary.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, default=book_summary.models.set_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_summary.Category', verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, default=book_summary.models.set_default_publisher, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_summary.Publisher', verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='bigcategory',
            field=models.ForeignKey(default=book_summary.models.set_default_bigcategory, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_summary.BigCategory', verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='author',
            field=models.ForeignKey(default=book_summary.models.set_default_author, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_summary.Author'),
        ),
    ]
