# Generated by Django 2.2.1 on 2019-05-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_summary', '0002_auto_20190526_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='投稿者'),
        ),
    ]
