# Generated by Django 2.0.13 on 2019-04-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_summary', '0002_auto_20190426_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
        migrations.AddField(
            model_name='books',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='summary',
            field=models.CharField(default='book', max_length=800),
            preserve_default=False,
        ),
    ]
