# Generated by Django 2.2.1 on 2019-06-08 03:41

import book_summary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_summary', '0002_topcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigcategory',
            name='topcategory',
            field=models.ForeignKey(default=book_summary.models.set_default_topcategory, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_summary.TopCategory', verbose_name='トップカテゴリ名'),
        ),
    ]
