# Generated by Django 2.2.1 on 2019-05-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_summary', '0003_auto_20190526_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, default='名無しさん', max_length=200, verbose_name='投稿者'),
        ),
    ]
