# Generated by Django 2.1.7 on 2019-06-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_summary', '0004_auto_20190621_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='公開日'),
        ),
    ]
