# Generated by Django 2.2.1 on 2019-06-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_summary', '0005_auto_20190628_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='公開日'),
        ),
    ]
