# Generated by Django 2.2.1 on 2019-06-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_summary', '0006_book_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
