# Generated by Django 2.2.1 on 2019-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_summary', '0007_remove_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='公開日'),
        ),
    ]
