# Generated by Django 2.2.1 on 2019-06-30 09:51

import book_summary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_summary', '0008_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='中カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='bigcategory',
            name='topcategory',
            field=models.ForeignKey(default=book_summary.models.set_default_topcategory, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_summary.TopCategory', verbose_name='大カテゴリ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, default=book_summary.models.set_default_category, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_summary.Category', verbose_name='小カテゴリ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='bigcategory',
            field=models.ForeignKey(default=book_summary.models.set_default_bigcategory, on_delete=django.db.models.deletion.SET_DEFAULT, to='book_summary.BigCategory', verbose_name='中カテゴリ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='小カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='topcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='大カテゴリ名'),
        ),
    ]
